name: Ubuntu & Windows CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configure
      shell: bash
      run: |
        mkdir build
        cmake -B build -S src -DCMAKE_BUILD_TYPE=Release

    - name: Build
      shell: bash
      run: cmake --build build

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-build
        path: build

    - name: Install
      shell: bash
      run: |
        mkdir install
        cmake --install build --prefix install

    - name: Upload install artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-install
        path: install
